bower.json

This will make applications depending on Bower to load Leaflet before Leaflet.markercluster.

Added dependencies in bower.json

---

build/deps.js
spec/index.html
spec/suites/RememberOpacity.js
src/MarkerCluster.Spiderfier.js
src/MarkerCluster.js
src/MarkerClusterGroup.js
src/MarkerOpacity.js

Extends L.Marker and wraps calls to setOpacity(0) and setOpacity(1).
Fixes Leaflet/Leaflet.markercluster#312

On becoming visible, markers retain their original opacity. 

---

src/MarkerClusterGroup.js

rounded zoom to work with fractional zoom levels

---

bower.json

So it is compatible with [wiredep](https://github.com/taptapship/wiredep)

Added "main" property to bower.json to make it compatible with wiredep

---

spec/suites/removeLayersSpec.js
src/MarkerClusterGroup.js

fix removeLayers when cluster is not on the map

---

README.md

Added reference to chunked addLayers explanation

---

README.md

with links to Leaflet.FeatureGroup.SubGroup and Leaflet.MarkerCluster.LayerSupport, following #591.

README added sub-plugins section

---

README.md

Remove emboldened 's' in README

Formatting typo

---

README.md
spec/index.html
spec/suites/unspiderfySpec.js
src/MarkerCluster.Spiderfier.js

add public unspiderfy method to MarkerClusterGroup to unspiderfy markers programmatically

unspiderfy

---

README.md
spec/suites/disableClusteringAtZoomSpec.js
src/MarkerClusterGroup.js

Implemented suggested modification of PR #634.
Should solve #633 and possibly help #648.

Spiderfy combined with disable clustering

---

package.json

Remove leaflet from peerDependencies (Leaflet/Leaflet#4534)

---

src/MarkerCluster.js

Re-visited the conditions order to avoid the 2 similar loops.

Simplified _recursively

---

README.md

Hi ! Since I went into this case #732 here is a PR to add explanations about installing jake and building the scripts, and then get this file `leaflet.markercluster-src.js`

Add install and build steps with jake

---

README.md
src/MarkerCluster.js

Allow paddling fitBounds options to zoomToBounds

---

CONTRIBUTING.md
README.md
example/marker-clustering-pane.html
spec/suites/PaneSpec.js
src/MarkerCluster.js
src/MarkerClusterGroup.js

As discussed in issue #785, this is a pull request that adds a pane option to markerClusterGroup. It uses code from @ghybs, but of course alters the initialize method instead of overriding it. Also included is a documentation update and an example.

Support optional pane

---

spec/suites/DistanceGridSpec.js
src/DistanceGrid.js

Fix for #836, see the individual commit messages. I hope the coding style is correct?

Fix #836: very small maxClusterRadius hangs browser

---

README.md
spec/suites/spiderfySpec.js
src/MarkerCluster.Spiderfier.js
src/MarkerClusterGroup.js

this pr addresses #467 . User will be able to provide custom function to calculate  spiderfy shape positions like that (example function makes spiderfy align markers in line, one by one): 
```
spiderfyShapePositions: function(count, centerPt) {
var distanceFromCenter = 35,
markerDistance = 45,
lineLength = markerDistance * (count - 1),
lineStart = centerPt.y - lineLength / 2,
res = [],
i;
res.length = count;
for (i = count - 1; i >= 0; i--) {
res[i] = new Point(centerPt.x + distanceFromCenter, lineStart + markerDistance * i);
}
return res;
}
```

add an ability to provide custom function for spiderfy shape positions

---

package.json

Hello this update will make sure to fix the vulnerability in uglify-js fixed in version 2.6.0. This will throw warnings on any repo that has vulnerabilities turned on (would suggest also adding it to this repo perhaps).
I did test running the scripts to make sure they dont break and all seems ok. but do please check any necessary things you have to 👍

chore(uglify-js): Update version

---

.travis.yml
Jakefile.js
build/rollup-config.js
package-lock.json
package.json
spec/karma.conf.js

Successor of #943 
As I wrote in #943 I'd really recommend to install Renovate to keep all those deps up to date and to early find issues.

Upgrade deps and Node version

---

src/MarkerClusterGroup.js

Spiderfy on keypress
