Leaflet/Leaflet.markercluster

- bower.json
Solves #462, reduces the bower distribution size ~7 times.
> bower.json: ignore tests and examples.

- bower.json
There was already a working and valid main section.
See [this issue](https://github.com/Leaflet/Leaflet.markercluster/issues/551)
> Revert "Added "main" property to bower.json to make it compatible with wiredep"

- README.md
Replaced constructors by factories in README documentation, as proposed in #500 ([docs] Replace object constructor with factory)
> Replaced constructors by factories

- src/MarkerClusterGroup.js
Following issue #503, slightly improved `zoomToShowLayer` to check that a proper callback function is passed. Also slightly simplified the event binding on `parent.spiderfy()` (using directly `this.once` instead of manually unbinding it).
> Improved zoomToShowLayer with callback check

- spec/suites/RefreshSpec.js
For some reason with PhantomJS only, the test process hangs quite often
with the addition of RefreshSpec test suite.
By avoiding anonymous functions in `beforeEach` and `afterEach` and re-using
objects whenever possible, the test process looks much more reliable.
> Improved reliability of RefreshSpec test suite for PhantomJS

- README.md
Corrected typo on line 134 and slightly improved explanations about `refreshIconOptions()` method.
Improved clarity of example for `L.Marker.refreshIconOptions` method.
> Corrected typo in README for refreshClusters()

- README.md
- spec/index.html
- spec/suites/animateOptionSpec.js
- src/MarkerCluster.Spiderfier.js
- src/MarkerClusterGroup.js
Deleted previous branch animationOption since I messed up trying to rebase...
This closed PR #576.
Following issues #382, #348 and PR #352, added a new option `animate` to `L.MarkerClusterGroup` to select the animation behaviour. This option affects zoomIn, zoomOut, addLayer, spiderfy and unspiderfy.
It defaults to true and its effect is ignored if `L.DomUtil.TRANSITION` is false, so that MCG keeps the current behaviour (it animates or not depending on `L.DomUtil.TRANSITION`) when this option is left unassigned.
The only difference is that its effect is determined at instantiation time instead of at script loading time.
To achieve this, this code removes the test condition when including the animation (or non-animation) methods. It adds all methods to prototype, and hooks to the …
> Added animate option

- spec/index.html
- spec/suites/RefreshSpec.js
- spec/suites/animateOptionSpec.js
- spec/suites/singleMarkerModeSpec.js
- src/MarkerClusterGroup.Refresh.js
- src/MarkerClusterGroup.js
Following issue #581, improved `refreshClusters()` method so that it detects `singleMarkerMode` and re-draws all passed markers as well, not only parent clusters. Took the opportunity to factorize code with `_addLayer()` method, creating a new `_overrideMarkerIcon()` method that re-styles the marker using the `iconCreateFunction` from clusters.
Added an extra test in RefreshSpec test suite to cover this case. Also re-factored it using `it2` wrapper to avoid hanging test process.
Also created the singleMarkerModeSpec test suite to test `singleMarkerMode` option and included it into the new suite into spec/index.
> Made refreshClusters to re-draw markers in singleMarkerMode

- src/MarkerCluster.js
- src/MarkerClusterGroup.js
Following the super interesting thread in #536, I succeeded in implementing the 3 optimizations:
- No bounds and weighted position computation during adding.
- No complete bounds and weighted position re-computation during remove.
- Reset LatLngBounds rather than re-create objects.
This was easier than I originally thought, and the patch is quite elegant I find: it flags clusters as having "dirty" bounds and position (using `_boundsNeedUpdate` new flag), in the same manner as `_iconNeedsUpdate`, so that at the end of the add / remove, we can call `this._topClusterLevel._recalculateBounds()` only once and refresh only clusters that need to be.
The performance gain is very substantial: about 5x for `addLayers` and 10x for `removeLayers`!
With the realworld.50000 example (without …
> Optimized performance of bulk addLayers and removeLayers

- README.md
- dist/MarkerCluster.css
- src/MarkerCluster.Spiderfier.js
- src/MarkerClusterGroup.js
Following #554 and #584, experimented CSS transition to perform the spiderfy legs animations (should follow their markers, except in the case of circleMarkers which do not animate, but the legs do animate).
[CSS transition support](http://caniuse.com/#feat=css-transitions) should be broader than [SMIL](http://caniuse.com/#feat=svg-smil), in particular for IE.
I still made up a demo page and hopefully we can get people to test on different environments?
http://ghybs.github.io/Leaflet.markercluster/animateSpiderfyNoSMIL/marker-clustering-spiderfyAnimation-noSMIL.html
Works for me on FF and Chrome, but definitely not on IE8...
I created a new CSS class "leaflet-cluster-spider-leg" to add the transition (copied opacity, added stroke-dashoffset). This class is always added to the legs (no …
> Replaced spiderfy legs animation from SMIL to CSS transition

- spec/suites/removeOutsideVisibleBoundsSpec.js
- src/MarkerClusterGroup.js
Following #512, created a new private method in MCG `_checkBoundsMaxLat` that corrects output of `_getExpandedVisibleBounds` when the latter reaches the CRS projection maximum latitude (typically for Web/Spherical Mercator).
In that case, it extends the latitude to Infinity (or -Infinity in Southern hemisphere) so that all markers and clusters beyond the limit are added to the map. Indeed, when user adds markers directly to the map (not through MCG), if their latitude is above the limit, the projection will floor their position to the limit, so they will be visible within the map.
Without the correction, the map view bounds (even expanded) never reaches the very high latitudes, and MCG never adds markers and clusters at those positions. Hence they are never visible, even though they are …
> Correct _getExpandedVisibleBounds for Max Latitude

- spec/suites/spiderfySpec.js
- src/MarkerClusterGroup.js
Current code in `_zoomOrSpiderfy` spiderfies at current zoom only if **all** child markers are at the **exact** same position (i.e. cluster bounds is a point) (or if we are at max zoom already obviously).
That means that if markers are at **slightly different** positions, but if they are all still in a single cluster at maximum zoom, clicking on the cluster will zoom to that max zoom level, but user will still see the "same" cluster, and no markers. And he/she will need a second click to trigger the spiderfy. This is exactly what the current code was trying to avoid.
Since current MCG does not display any clue about the true markers position anyway (spider legs point at the cluster position, not at true positions), there is no point zooming to maximum zoom in that case either.
This PR …
> Spiderfy at current zoom if all child markers still in single cluster at maxZoom

- spec/suites/removeOutsideVisibleBoundsSpec.js
- src/MarkerCluster.Spiderfier.js
L.Circle has `_latLng` and as such can be clustered and spiderfied. However, when unspiderfying, L.Circle does not have the `setOpacity` nor `setZIndexOffset` methods of L.Marker.
Also corrected removeOutsideVisibleBoundsSpec test suite.
> Correct unspiderfy vector

- README.md
This plugin directly adds new methods to MCG. It becomes possible "freezing" clusters at a given arbitrary zoom level. In particular, freezing at maxZoom + 1 makes as if MCG was disabled. Freezing at maxZoom makes as if MCG was disabled except for the bottom-most clusters with spiderfication.
Found following related issues / feature requests: #98, #112, #173, #339, #534, #552.
It goes also a step forward #499.
However #399 would probably still need something more sophisticated as it would require applying the same principle on a cluster's zoom basis rather than for the whole group's zoom.
> Added sub-plugin MCG.Freezable (on to README page)

- src/MarkerCluster.Spiderfier.js
When animating unspiderfy there is a timeout. Fire event when done to let users know unspiderfy is complete.
> Fire unspiderfied event

- example/marker-clustering-geojson.html
The existing code is not broken, this just seems to to improve readability/best practice and may prevent a future bug.
> Added a couple of missing semi-colons in geojson example

- spec/suites/zoomAnimationSpec.js
- src/MarkerClusterGroup.js
Same as #344, which was corrected by commit 254198ad47d73ddb7177c6aefde78561046d8c0c in leaflet-0.7 branch only. Do the same in master branch (for Leaflet 1.0.0) as well.
Also added a dedicated test spec in zoomAnimationSpec test suite.
Took the opportunity to refactor the test suite to avoid PhantomJS memory leak.
> Corrected #529 in master (Leaflet 1.0.0)

- package.json
in `package.json` to specify the Leaflet version for which Leaflet.markercluster is compatible with, following issue #639.
`peerDependencies` as described in https://docs.npmjs.com/files/package.json#peerdependencies
Maybe take the opportunity to loosen the Leaflet version?
And also to change the Leaflet.markercluster version?
> Replaced `dependencies` by `peerDependencies`

- README.md
Following #671, replaced all links on README page to gh-pages that were using `http://leaflet.github.com` to `http://leaflet.github.io`, so that we avoid GitHub redirect from `http://XYZ.github.com` to `https://XYZ.github.io` (with `https` protocol, which is incompatible with current Leaflet CDN).
> Replaced links to gh-pages by github.io

- src/MarkerClusterGroup.Refresh.js
- src/MarkerClusterGroup.js
Unified invalidating of icons to match that of bounds (#584).
The improvement is most (only?) apparent with `addLayers` when function for generating icon is complex (e.g. uses `getAllChildMarkers`) and the view is zoomed out, so that markers are added to existing cluster with a high humber of points. Basic example (time is written to console):
- original: https://qedsoftware.github.io/Leaflet.markercluster/icon-performance/marker-clustering-realworld.50000.html
- optimized: https://qedsoftware.github.io/Leaflet.markercluster/icon-performance/marker-clustering-realworld.50000-after.html
With such a basic example, on latest Safari & Chrome it's a reduction from ~6s to ~300ms. In our case (icons based on [PruneCluster categories](http://sintef-9012.github.io/PruneCluster/examples/random.10000 …
> Optimized performance of bulk add with complex icon create function

- src/MarkerClusterGroup.js
Get the map zoom from internal `_zoom` in `addLayer` and `_animationAddLayer` methods, for compatibility with MCG.Freezable plugin (see issue ghybs/Leaflet.MarkerCluster.Freezable#1).
In normal situation (i.e. without Freezable plugin), the 2 should differ only momentarily at the end of a zoom, before the `_zoomEnd` listener is called, and until that listener completes.
If `addLayer` happens before the listener is called, it should perform as if the zoom did not occur yet, then `_zoomEnd` proceeds with the new layer / cluster without issue.
`addLayer` should not be able to execute in the middle of `_zoomEnd`, as there is no asynchronous task involved, except for the end of the zoom animation, where previous clusters are collected. For that one, `_zoom` is already updated to equal …
> Get map zoom from internal _zoom for compatibility with Freezable sub-plugin

- README.md
- Improved plugin installation instructions (added local copy and CDN options), should address #713
- Corrected TOC order for first section
Local copy is a link to directly download `v1.0.0` release zip archive from GitHub.
CDN uses unpkg (based on npm), like Leaflet officially recommended CDN.
> README plugin install details

- src/MarkerClusterGroup.js
The exception was that the function 'this._childmarkerMoved' could not be found because the context was not known. So I passed the context in the 'eachLayer' function
> Fixed leaflet 1.0.2 bug where clearLayers would throw an exception

- spec/suites/zoomAnimationSpec.js
- src/MarkerClusterGroup.js
Hello,
this will fix https://github.com/Leaflet/Leaflet.markercluster/issues/739
Timeout allows to handle map movestart event before checking it execution, so layer parent won't spiderfy when move start.
Fixed example from issue http://codepen.io/anon/pen/wgBBJV
> Fixed zoomToShowLayer() markers disappearing bug

- src/MarkerClusterGroup.js
Self explanatory, 0 is a valid zoom level as well.
> Bugfix, disableClusteringAtZoom being 0 is treated the same as null

- example/geojson.html
- example/marker-clustering-convexhull.html
- example/marker-clustering-custom.html
- example/marker-clustering-dragging.html
- example/marker-clustering-everything.html
- example/marker-clustering-geojson.html
- example/marker-clustering-realworld-maxzoom.388.html
- example/marker-clustering-realworld-mobile.388.html
- example/marker-clustering-realworld.10000.html
- example/marker-clustering-realworld.388.html
- example/marker-clustering-realworld.50000.html
- example/marker-clustering-singlemarkermode.html
- example/marker-clustering-spiderfier.html
- example/marker-clustering-zoomtobounds.html
- example/marker-clustering-zoomtoshowlayer.html
- example/marker-clustering.html
- example/old-bugs/add-1000-after.html
- example/old-bugs/add-markers-offscreen.html
- example/old-bugs/add-remove-before-addtomap.html
- example/old-bugs/animationless-zoom.html
- example/old-bugs/click-cluster-at-screen-edge.html
- example/old-bugs/disappearing-marker-from-spider.html
- example/old-bugs/doesnt-update-cluster-on-bottom-level.html
- example/old-bugs/remove-add-clustering.html
- example/old-bugs/remove-when-spiderfied.html
- example/old-bugs/removelayer-after-remove-from-map.html
- example/old-bugs/setView-doesnt-remove.html
- example/old-bugs/zoomtoshowlayer-doesnt-need-to-zoom.html
- example/old-bugs/zoomtoshowlayer-doesnt-zoom-if-centered-on.html
- example/remove-geoJSON-when-spiderfied.html
on all example and debug pages (i.e. 30 HTML files), so that on `github.io`, there is no "mixed content" warning anymore.
Switch Leaflet CDN from cdnjs to "official" unpkg.com.
Switch `leaflet.js` to `leaflet-src.js` (14 files).
Also updated the copyright link to OSM using the "official" URL (with https), even though it takes more bytes than the shortcut URL. But at least it is easier for visitors to understand the relationship between the link text and the URL.
(cherry picked from commit b5afe4f)
=> same as PR https://github.com/Leaflet/Leaflet.markercluster/pull/795 but for `gh-pages` branch, so that it takes effect right now on online demos (`github.io`).
> Refactor(examples/debug): use HTTPS for CDN, Tiles & OSM link (gh-pages)

- example/geojson.html
- example/marker-clustering-convexhull.html
- example/marker-clustering-custom.html
- example/marker-clustering-dragging.html
- example/marker-clustering-everything.html
- example/marker-clustering-geojson.html
- example/marker-clustering-realworld-maxzoom.388.html
- example/marker-clustering-realworld-mobile.388.html
- example/marker-clustering-realworld.10000.html
- example/marker-clustering-realworld.388.html
- example/marker-clustering-realworld.50000.html
- example/marker-clustering-singlemarkermode.html
- example/marker-clustering-spiderfier.html
- example/marker-clustering-zoomtobounds.html
- example/marker-clustering-zoomtoshowlayer.html
- example/marker-clustering.html
- example/old-bugs/add-1000-after.html
- example/old-bugs/add-markers-offscreen.html
- example/old-bugs/add-remove-before-addtomap.html
- example/old-bugs/animationless-zoom.html
- example/old-bugs/click-cluster-at-screen-edge.html
- example/old-bugs/disappearing-marker-from-spider.html
- example/old-bugs/doesnt-update-cluster-on-bottom-level.html
- example/old-bugs/remove-add-clustering.html
- example/old-bugs/remove-when-spiderfied.html
- example/old-bugs/removelayer-after-remove-from-map.html
- example/old-bugs/setView-doesnt-remove.html
- example/old-bugs/zoomtoshowlayer-doesnt-need-to-zoom.html
- example/old-bugs/zoomtoshowlayer-doesnt-zoom-if-centered-on.html
- example/remove-geoJSON-when-spiderfied.html
on all example and debug pages (i.e. 30 HTML files), so that on `github.io`, there is no "mixed content" warning anymore.
Switch Leaflet CDN from cdnjs to "official" unpkg.com + with SRI check.
Switch `leaflet.js` to `leaflet-src.js` (14 files).
Also updated the copyright link to OSM using the "official" URL (with https), even though it takes more bytes than the shortcut URL. But at least it is easier for visitors to understand the relationship between the link text and the URL.
> Refactor(examples/debug): use HTTPS for CDN, Tiles & OSM link

- README.md
instead of `http`, now that we have `https` CDN for Leaflet.
> Docs(README): use https for demo links

- example/marker-clustering-pane.html
- src/MarkerClusterGroup.js
Hi,
Follows PR https://github.com/Leaflet/Leaflet.markercluster/pull/819 which introduced `clusterPane` option.
This PR proposes to move the initialization of `clusterPane` from the `initialize` function into the dedicated `options` field, like most other options.
There is no real need to set it "manually" during initialization phase, instead of letting Leaflet class mechanism retrieve it automatically.
The case of `iconCreateFunction` option is different because it refers to a function that is defined in the same class. Therefore this function is not accessible until Leaflet finishes preparing the class.
But even that could be worked around, for example by moving that function to file context (it is actually like a static function, it is not related to an instance / it does not depend on …
> Refactor(options): move clusterPane into options field

- src/MarkerCluster.Spiderfier.js
Hi,
This PR increases the minimum spiderfication leg length, so that markers (especially important for Circle Markers, which are displayed under DivIcons by default) are positioned outside the default Cluster icon in all situations.
**When the spiderfication is a circle (i.e. for < 9 child markers)**, this PR uses a minimum leg length of 35 pixels, in order to extend beyond the default cluster icon (size 40, hence radius 20px), including after the circle offset (10px).
2 children with fix: ![screenshot_20171125_124310](https://user-images.githubusercontent.com/12232803/33228925-37d960a4-d1de-11e7-9fa5-23da713aa665.png) ![screenshot_20171125_110050](https://user-images.githubusercontent.com/12232803/33228251-f7ed8500-d1cf-11e7-8ff8-5d4002c8cd68.png) w/o fix: …
> Fix(Spiderfier): min leg length for circle and skip 1st pos for spiral

- Jakefile.js
Hi,
Fix https://github.com/Leaflet/Leaflet.markercluster/issues/919
This PR explicitly specifies `lint` and `build` jake tasks as [`async`](http://jakejs.com/docs#tasks), to avoid trying to minify while build (rollup) has not completed yet.
> Fix(jake): specify async tasks to make sure uglify waits for build

- spec/suites/zoomAnimationSpec.js
- src/MarkerClusterGroup.js
Hi,
Fix https://github.com/Leaflet/Leaflet.markercluster/issues/904
As explained in the above issue, [`zoomToShowLayer`](https://github.com/Leaflet/Leaflet.markercluster#other-group-methods) method currently does not work well when clustered Markers do not use Icons (typically Circle Markers).
I will push the PR in 2 steps:
1. Only with the added test to show that it fails in current state.
2. With fix to show that now it passes.
With this fix, it should also be in a better position to handle non-icon-based Cluster Markers as well, although I suspect there might be other places that also need a fix to provide full compatibility.
> Fix(zoomAnim): add compatibility with non-icon-based Markers

- spec/suites/AddLayer.MultipleSpec.js
- spec/suites/AddLayersSpec.js
- src/MarkerClusterGroup.js
Hi again,
Fix https://github.com/Leaflet/Leaflet.markercluster/issues/879
Add the call to `_unsiperfy` within the `process` subtask of `addLayers`, so that it works even if for some reason a cluster has been spiderfied while `addLayers` is in the middle of processing.
As previously, I will push this PR in 2 steps (test, then fix).
> Fix(addLayers): unspiderfy before adding new Marker(s)

- package.json
The `style` attribute is useful when using `Leaflet.markerCluster` with most node bundling systems (e.g. Browserify, Webpack) or any setup that uses PostCSS.
Note - only one of the two CSS files is exposed with this change. The `package.json` `style` attribute doesn't have a standardised behaviour but in the most popular implementations accepts only a string (as opposed to an array of strings). There are two css files shipped with `Leaflet.markerCluster`, but only [`MarkerCluster.css`](https://github.com/Leaflet/Leaflet.markercluster/blob/master/dist/MarkerCluster.css) is essential (`MarkerCluster.Default.css` is only needed for some use-cases).
> Expose essential CSS in package.json style attr (fixes #906)

- src/MarkerClusterGroup.js
This is adding invisible "markers" information with aria-label for each marker cluster to fix https://github.com/Leaflet/Leaflet.markercluster/issues/1006 and each marker cluster now reads better "N markers" not just "N".
> Adding "markers" for clusters in aria-label for accessibility

- src/MarkerClusterGroup.js
Related to #1101
If default has been prevented on the event coming to ```L.MarkerClusterGroup``` cancel further execution in ```_zoomOrSpiderfy```. This allows for custom logic on whether a cluster is allowed to be zoomed-in / spiderfyed or not.
> Cancel zoomOrSpiderfy if default prevented
